#!/bin/bash

if [ -z $GOTO_PATH ]; then
    echo "goto: 'GOTO_PATH' is not defined" 1>&2
    return 1
fi
case $1 in
    add|list|delete|get)
        $GOTO_PATH/src/goto.py $1 "${@:2}"
        ;;
    -h|--help)
        $GOTO_PATH/src/goto.py $1 
        ;;
    *)
        if [ -d "$GOTO_PATH/.goto/$1" ]; then
            cd -P "$GOTO_PATH/.goto/$1"
        elif [ "$1" = "show-all-if-ambiguous" ]; then
            :
        else
            echo "goto: alias '$1' does not exist" 1>&2
            return 1
        fi
        ;;
esac

